### ISSUE TITLE
require kramdown-parser-gfm

### ISSUE THREAD

**Issue by parasew** [slideshow-s9/docs#1]
since gfm is not in kramdown anymore (see https://kramdown.gettalong.org/parser/gfm.html ) the kramdown-parser-gfm should be required or be in the dependency list in order for slideshow to work!

**Comment by geraldb** [comment]
@parasew  Thanks for reporting. Good catch. The slideshow library / tool needs to get updated for kramdown v2.0.

**Comment by parasew** [comment]
require 'kramdown-parser-gfm' does the trick

**Comment by geraldb** [comment]
Thanks. Added the new gem and require.  Pushed / uploaded a new version, that is. 4.1. Cheers.  PS: Find the reveal.js template pack @ <https://github.com/slideshow-templates/slideshow-reveal.js>.
